/**
 * Build an frpc TOML config file from a session payload.
 */
import type { IssueSessionRequest } from "./types.js";

export interface FrpcConfigInput {
  serverAddr: string;
  serverPort: number;
  token: string;
  proxyName: string;
  protocol: "http" | "https" | "tcp" | "udp";
  localHost: string;
  localPort: number;
  managedHostname?: string;
  customDomains?: string[];
}

/**
 * Render an frp >=0.52 TOML config. Uses tokens rather than OIDC.
 *
 * Domain handling:
 *  - HTTP/HTTPS proxies use `customDomains` (which can include both the
 *    managed subdomain and user custom domains).
 *  - TCP/UDP proxies do not support customDomains and expose a
 *    remotePort instead (not written here — the server allocates).
 */
export function buildFrpcConfig(input: FrpcConfigInput): string {
  const lines: string[] = [];
  lines.push(`# Generated by @vibecontrols/vibe-plugin-tunnel-vibetunnels`);
  lines.push(`serverAddr = "${input.serverAddr}"`);
  lines.push(`serverPort = ${input.serverPort}`);
  lines.push("");
  lines.push("[auth]");
  lines.push(`method = "token"`);
  lines.push(`token = "${input.token}"`);
  lines.push("");
  lines.push('log.to = "console"');
  lines.push('log.level = "info"');
  lines.push("");

  lines.push("[[proxies]]");
  lines.push(`name = "${input.proxyName}"`);
  lines.push(`type = "${input.protocol}"`);
  lines.push(`localIP = "${input.localHost}"`);
  lines.push(`localPort = ${input.localPort}`);

  if (input.protocol === "http" || input.protocol === "https") {
    const domains: string[] = [];
    if (input.managedHostname) domains.push(input.managedHostname);
    if (input.customDomains && input.customDomains.length > 0) {
      domains.push(...input.customDomains);
    }
    if (domains.length > 0) {
      lines.push(
        `customDomains = [${domains.map((d) => `"${d}"`).join(", ")}]`,
      );
    }
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Pull required frp control-plane fields out of a session payload. Throws
 * with a descriptive error when anything is missing.
 */
export function extractFrpsHint(req: IssueSessionRequest): {
  serverAddr: string;
  serverPort: number;
  token: string;
  proxyName: string;
  managedHostname?: string;
  shardId?: string;
  sessionId?: string;
} {
  const payload = req.controlPlanePayload ?? {};
  const serverAddr = payload["serverAddr"] ?? payload["shardHost"];
  const serverPort =
    payload["serverPort"] ?? payload["shardPort"] ?? payload["port"];
  const token = payload["token"] ?? payload["authToken"];
  const proxyName =
    payload["proxyName"] ?? payload["name"] ?? payload["serviceName"];
  if (typeof serverAddr !== "string") {
    throw new Error("controlPlanePayload.serverAddr is required");
  }
  if (typeof serverPort !== "number") {
    throw new Error("controlPlanePayload.serverPort is required");
  }
  if (typeof token !== "string") {
    throw new Error("controlPlanePayload.token is required");
  }
  if (typeof proxyName !== "string") {
    throw new Error("controlPlanePayload.proxyName is required");
  }
  return {
    serverAddr,
    serverPort,
    token,
    proxyName,
    managedHostname:
      typeof payload["managedHostname"] === "string"
        ? (payload["managedHostname"] as string)
        : undefined,
    shardId:
      typeof payload["shardId"] === "string"
        ? (payload["shardId"] as string)
        : undefined,
    sessionId:
      typeof payload["sessionId"] === "string"
        ? (payload["sessionId"] as string)
        : undefined,
  };
}
